# Generated by Django 5.0.4 on 2024-05-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment_remove_customuser_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
