# Generated by Django 5.0.4 on 2024-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_payment_createdat_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
